title: Volti0's Malware Den
description: "El sitio más cabron de malware"
author:
  name: "The one and only Volti0"
  email: "nilosueñes"
  url: "https://volti0.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: "_posts/"
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Volti0"
year : "2023"
