title: Suspect's Malware Den
description: "Sit and enjoy"
author:
  name: "Number One Suspect"
  email: "nilosueñes"
  url: "https://suspect.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: "_posts/"
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Suspect"
year : "2024"
